# Generated by Django 5.1.1 on 2025-05-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_trialsolution"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialsolution",
            name="hint",
            field=models.TextField(
                blank=True,
                help_text="A short hint for this trial (shown after purchase).",
            ),
        ),
    ]
